version: "3.7"

services:
    # image project
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - laravel
        mem_limit: 512m

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "9090:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel
        mem_limit: 256m
    # db mysql
    db:
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-gymconnect}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
            MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
            MYSQL_USER: ${DB_USERNAME:-username}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3388:3306"
        expose:
            - "3388"
        networks:
            - laravel
        mem_limit: 1024m
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        networks:
            - laravel
        environment:
            PMA_HOST: host.docker.internal
            PMA_PORT: 3388
            PMA_USER: root
            PMA_PASSWORD: root
        ports:
            - '8090:80'
        volumes:
            - /sessions
        mem_limit: 256m
    # redis
    redis:
        image: redis:latest
        networks:
            - laravel
        mem_limit: 256m
networks:
    laravel:
        driver: bridge